version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_HOST_PORT}:${PGADMIN_PORT}

  task-flow-api:
    container_name: task-flow-api
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    volumes:
      - .:/task-flow-api
    command: sh -c "pnpm migrations:run && dumb-init node dist/main.js"
